name: Build container image

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production
    steps:

    - name: checkout files in repo
      uses: actions/checkout@main

    - name: update jupyter dependencies with repo2docker
      uses: jupyterhub/repo2docker-action@master
      with: # make sure username & password/token matches your registry
        #DOCKER_USERNAME: ${{ secrets.QUAY_USERNAME }}
        #DOCKER_PASSWORD: ${{ secrets.QUAY_PASSWORD }}
        ## I (Fredy) added explicit credentials for Quay.io 
        DOCKER_USERNAME: alfredoquevedo+unitefa_hub_image_builder
        DOCKER_PASSWORD: H3U4SS6J9C4INQIMXN60KPK131XV6R7RZ9AC1SAMBD51O5QXQ400C3I31WTOE60U
        DOCKER_REGISTRY: "quay.io"
        IMAGE_NAME: "alfredoquevedo/hub-environment"
